# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: cd-webhooks-forwarder
  namespace: cd-webhooks-forwarder
spec:
  type: ClusterIP
  ports:
    - name: cd-webhooks-forwarder
      port: 80
      targetPort: 3000
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-webhooks-forwarder
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
        - name: cd-webhooks-forwarder
          image: lhr.ocir.io/lrdyqp2xtoja/cd-webhooks-forwarder
          env:
            - name: RUST_LOG
              value: cd_webhooks_forwarder=trace
          resources:
            requests:
              cpu: 5m
              memory: 1Mi
            limits:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: oracle-container-registry
---
